name: Lint

on:
    push:
        branches: [ main ]
    pull_request_target:
      types: [ labeled ]

jobs:
    phpcs:
        name: PHPCS

        continue-on-error: false

        runs-on: ubuntu-latest

        if: contains(github.event.pull_request.labels.*.name, 'safe to test')

        steps:
            - uses: actions/checkout@v2

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: 8.0
                  extensions: posix, dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick
                  coverage: none

            - name: Install dependencies
              run: |
                composer config "http-basic.nova.laravel.com" "${{ secrets.NOVA_USERNAME }}" "${{ secrets.NOVA_LICENSE_KEY }}"
                composer upgrade --no-interaction --no-suggest

            - name: PHP-8 compatible PHPCS
              run: vendor/bin/phpcs

    tlint:
        name: TLint

        continue-on-error: false

        runs-on: ubuntu-latest

        if: contains(github.event.pull_request.labels.*.name, 'safe to test')

        steps:
            - uses: actions/checkout@v1

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: 8.0
                  extensions: posix, dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick
                  coverage: none

            - name: Install dependencies
              run: |
                composer config "http-basic.nova.laravel.com" "${{ secrets.NOVA_USERNAME }}" "${{ secrets.NOVA_LICENSE_KEY }}"
                composer install --no-interaction --no-suggest

            - name: Tlint Lint
              run: vendor/bin/tlint
